### PR TITLE
Cleanup unnecessary references.

### PR DESCRIPTION
**Pull request by jaliyaudagedara**
These direct package references are unncessary as those can be resolved via existing project references.

### CODE REVIEW

**Comment by davidmrdavid** [comment]
@jaliyaudagedara: I'm happy to take this change, but can you please resolve the conflicts first?

**Comment by jaliyaudagedara** [comment]
@davidmrdavid, cool, rebased.

**Review by davidmrdavid — APPROVED** [review]

**Comment by davidmrdavid** [comment]
LGTM, thank you for doing this, very much appreciated!

**Comment by jaliyaudagedara** [comment]
@davidmrdavid of course, thanks for merging👍

**Pull request merged**
